### ISSUE TITLE
IEEEmadC

### ISSUE THREAD

**Issue by SangramChavan** [ozandndar/Empathy#1]
Your apps looks good, nice UI. Can you please add a table in your redme? sharing an example below.

Example: App Name (Hyperlink to executable file) | Repo name (Hyperlink to repo) | description (short description of app in few words) | Choose any license e.g. MIT (Hyperlink to Licence)| UK (Location)| Name of members (Hyperlink to Github profiles that contributed to the project) |

**Comment by ozandndar** [comment]
Hi Sangram,

I think there was a misunderstanding. Here is the project link.
https://github.com/ozandndar/IEEEmadC-wiki

Sangram Chavan <notifications@github.com>, 20 Ara 2019 Cum, 17:40 tarihinde
şunu yazdı:
