### ISSUE TITLE
IEEEmadC 

### ISSUE THREAD

**Issue by SangramChavan** [ozandndar/Empathy#2]
Please share the executable file in the repo?

**Comment by ozandndar** [comment]
https://github.com/ozandndar/Empathy/
This is the executable file. You will see the installation guideline blow in the description. If you don't have a react native development environment , follow the instructions in this doc -> https://facebook.github.io/react-native/docs/getting-started

Note: I used yarn instead npm for packages and you should be using yarn to execute the project.
